#!/usr/bin/env Rscript
# ============================================================
# Summary Table & Figures: Species by Order/Family and Distance to
# the Dangermond Preserve Boundary
# ============================================================
# Dangermond Project — Data Acquisition Step 7
#
# Tasks:
#   1) Load the per-species nearest-record table (Step 6, output (b):
#      each in-extent species' true closest record, even if that
#      specific record's own latitude falls outside the band — see
#      "Distance source" below for why this one and not output (a))
#   2) Bin each species' distance into: 0 km (inside), 0-1 km, 1-5 km,
#      5-10 km, 10-25 km, 25-50 km, and >=50 km (see "Beyond 50km" below)
#   3) Build a species-count table cross-tabbed by order, family, and
#      distance bin
#   4) Save a bar figure: distance bin on the x-axis, one bar per order
#      within each bin (grouped/clustered)
#   5) Save a second bar figure with the same layout (distance bin on
#      the x-axis, one bar per order within each bin) but each order's
#      bar is now stacked, segmented by the families within that order
#      — see "Order+family chart design" below
#
# DISTANCE SOURCE: uses Step 6's "including outside extent" output
# rather than "within extent only" — i.e. each species' true closest
# approach to the Preserve, even from a record whose own latitude falls
# outside the band. Confirmed with Step 6's own test case: some species
# only reveal their true closest distance once out-of-band records are
# considered, so using the within-extent-only figure here would
# overstate distance (and could put a species in the wrong bin) for any
# species where that applies.
#
# BEYOND 50KM: the requested bins only cover up to 25-50 km. Species
# whose closest record is 50 km or farther get a "50+ km" catch-all bin
# rather than being silently dropped — every in-extent species appears
# somewhere in the table.
#
# BIN BOUNDARIES: read literally from "0, 0<1 km, 1<5km, 5<10km,
# 10<25km, 25<50km" — the 0 km bin is the single point distance == 0
# (i.e. inside the Preserve); every other bin is [lower, upper), so a
# species at exactly 5 km falls in "5-10 km," not "1-5 km." Implemented
# with explicit case_when() logic rather than base R cut(), because the
# first bin (an exact point) doesn't fit cut()'s usual
# all-open-or-all-closed interval convention.
#
# ORDER+FAMILY CHART DESIGN: the second figure keeps the exact same
# frame as the first (distance bin on the x-axis, one dodged bar per
# order within each bin, same colors/order for each order across both
# figures) but each order's bar is now stacked into segments — one per
# family within that order — using shades of that order's own color:
# darker/fuller shade = more species, lighter tint = fewer. E.g.
# Hymenoptera's bar segments are all shades of Hymenoptera's blue, with
# its most numerous family getting the full/darkest blue and its least
# numerous family the lightest tint.
#
# ggplot2 doesn't have a single built-in position that dodges by one
# grouping (order) AND stacks by another (family) within each dodge slot
# at the same time — position_dodge() and position_stack() each handle
# only one grouping. The standard technique (and the one used here) is
# to compute each order's dodge offset manually as a numeric x position
# (distance-bin index + a per-order offset, same width for every bin so
# bar widths stay consistent regardless of which orders happen to be
# present in a given bin — the same "preserve=single" behavior the first
# chart gets from position_dodge2), then let geom_col's default stacking
# handle the family segments within each of those now-unique x positions.
# The bin labels are restored afterward as axis text.
#
# LEGEND: a true nested legend (an "Hymenoptera" header with its
# families listed under it) isn't something ggplot2 supports natively
# without extra layout tooling. The practical equivalent used here:
# legend entries are labeled "Order: Family" and ordered so every
# family within the same order sits adjacent to it in the legend, in
# the same shade sequence as its bar segment — so the grouping still
# reads clearly from color + adjacency + label, just without a literal
# section-header rule between orders.
#
# COLOR: base hues are the same validated categorical palette used
# throughout this project (8 colorblind-safe hues, fixed order — see
# `references/palette.md` in the `dataviz` skill), assigned to orders by
# descending total species count, with any order beyond the 8th folded
# into a neutral "Other" bucket rather than generating a new hue — same
# rule as the first chart, and the two charts assign the same color to
# the same order. Within an order, family shades run from that order's
# full base color (its most numerous family) down to a lightened tint
# (its least numerous), generated by blending the base hex toward white
# — not a second independently-chosen hue, so it reads as "shades of
# one color" rather than a second unrelated categorical scale. Not
# capped if an order has many families — with enough families the
# lightest shades could become hard to tell apart, which hasn't come up
# in testing but is worth watching once real data is used; folding an
# order's smallest families into an "(other Order)" bucket would be the
# natural next step if that happens.
# ============================================================

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)

# Species counts are always non-negative integers — force integer-only
# y-axis ticks rather than ggplot's default, which can land on 0.5 etc.
# for small ranges.
integer_breaks <- function(x) {
  rng <- range(x, na.rm = TRUE)
  b <- pretty(rng, n = 5)
  b <- b[b == floor(b)]
  if (length(b) < 2) b <- seq(floor(rng[1]), ceiling(rng[2]) + 1)
  b
}

# ------------------------------------------------------------
# USER INPUTS — update paths if needed
# ------------------------------------------------------------
infile <- "../06-boundary-distance/output/nearest_record_per_species_including_outside_extent.csv"

outdir <- "./output"
outfile_table             <- file.path(outdir, "species_by_order_family_distance.csv")
outfile_order_chart       <- file.path(outdir, "species_by_order_and_distance.png")
outfile_order_family_chart <- file.path(outdir, "species_by_order_and_family_stacked.png")
# ------------------------------------------------------------

dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

# Validated categorical palette (fixed order — see dataviz skill /
# references/palette.md for the source and its CVD validation)
categorical_palette <- c(
  "#2a78d6", # 1 blue
  "#eb6834", # 2 orange
  "#1baf7a", # 3 aqua
  "#eda100", # 4 yellow
  "#e87ba4", # 5 magenta
  "#008300", # 6 green
  "#4a3aa7", # 7 violet
  "#e34948"  # 8 red
)
other_color <- "#9c9a8c" # neutral gray for any order beyond the 8th

# Blend a base hex color toward white by `amount` (0 = the base color
# itself, 1 = white) — used to generate within-order family shades.
lighten_hex <- function(hex, amount) {
  base_rgb <- grDevices::col2rgb(hex) / 255
  new_rgb <- base_rgb + (1 - base_rgb) * amount
  grDevices::rgb(new_rgb[1, ], new_rgb[2, ], new_rgb[3, ])
}

# ------------------------------------------------------------
# 1) Load Step 6's per-species nearest-record table
# ------------------------------------------------------------
message("Reading input file...")
df <- read_csv(infile, show_col_types = FALSE)
message(sprintf("Loaded: %d records (should be one row per in-extent species)", nrow(df)))

species_col <- if ("scientificName_clean" %in% names(df)) "scientificName_clean" else "scientificName"

required_cols <- c(species_col, "order", "family", "distance_to_preserve_km")
missing_cols <- setdiff(required_cols, names(df))
if (length(missing_cols) > 0) {
  stop(sprintf(
    paste(
      "Missing required column(s): %s.",
      "This step needs 'order' and 'family' (standard Darwin Core taxonomic",
      "fields) to be present in the merged dataset all the way through Steps",
      "2-4 — check that both GBIF and Symbiota exports actually include",
      "them, and that Step 3's column-header report didn't flag them as",
      "missing from one source."
    ),
    paste(missing_cols, collapse = ", ")
  ))
}

if (any(duplicated(df[[species_col]]))) {
  warning("Input has more than one row for at least one species — expected exactly one row per species from Step 6's output (b). Counts below may be inflated for those species.")
}

# ------------------------------------------------------------
# 2) Bin each species' distance
# ------------------------------------------------------------
bin_levels <- c("0 km (inside)", "0-1 km", "1-5 km", "5-10 km",
                 "10-25 km", "25-50 km", "50+ km")

assign_distance_bin <- function(d) {
  case_when(
    is.na(d)             ~ NA_character_,
    d == 0                ~ "0 km (inside)",
    d > 0  & d < 1         ~ "0-1 km",
    d >= 1  & d < 5         ~ "1-5 km",
    d >= 5  & d < 10        ~ "5-10 km",
    d >= 10 & d < 25        ~ "10-25 km",
    d >= 25 & d < 50        ~ "25-50 km",
    d >= 50                ~ "50+ km",
    TRUE                  ~ NA_character_
  )
}

df <- df %>%
  mutate(distance_bin = factor(assign_distance_bin(distance_to_preserve_km),
                                levels = bin_levels))

n_unbinned <- sum(is.na(df$distance_bin))
if (n_unbinned > 0) {
  warning(sprintf("%d record(s) could not be binned (missing/invalid distance) and are excluded from the table and figures.", n_unbinned))
}

df_binned <- df %>% filter(!is.na(distance_bin))

if (nrow(df_binned) == 0) {
  stop("No species left to summarize after binning — check that the input file actually has species with a usable distance_to_preserve_km value.")
}

# Fill missing order/family with an explicit label rather than silently
# dropping those species from the taxonomic breakdown
df_binned <- df_binned %>%
  mutate(
    order  = ifelse(is.na(order)  | order  == "", "(order not recorded)",  order),
    family = ifelse(is.na(family) | family == "", "(family not recorded)", family)
  )

# ------------------------------------------------------------
# 3) Species-count table by order, family, distance bin
# ------------------------------------------------------------
message("\nBuilding order x family x distance-bin summary table...")

long_counts <- df_binned %>%
  group_by(order, family, distance_bin) %>%
  summarise(n_species = n_distinct(.data[[species_col]]), .groups = "drop")

summary_table <- long_counts %>%
  tidyr::complete(distance_bin = factor(bin_levels, levels = bin_levels),
                   tidyr::nesting(order, family), fill = list(n_species = 0)) %>%
  tidyr::pivot_wider(names_from = distance_bin, values_from = n_species, values_fill = 0) %>%
  mutate(Total = rowSums(across(all_of(bin_levels)))) %>%
  arrange(order, family)

totals_row <- summary_table %>%
  summarise(
    order = "TOTAL", family = "",
    across(all_of(c(bin_levels, "Total")), sum)
  )

summary_table_with_totals <- bind_rows(summary_table, totals_row)

write_csv(summary_table_with_totals, outfile_table)
message(sprintf("Summary table written to:\n  %s", outfile_table))
message(sprintf("In-extent species covered: %d", sum(totals_row$Total)))

# ------------------------------------------------------------
# 4) Order chart — distance bin on x-axis, one bar per order per bin
# ------------------------------------------------------------
message("\nBuilding order-level chart...")

order_counts <- df_binned %>%
  group_by(order, distance_bin) %>%
  summarise(n_species = n_distinct(.data[[species_col]]), .groups = "drop")

order_totals <- order_counts %>%
  group_by(order) %>%
  summarise(total = sum(n_species), .groups = "drop") %>%
  arrange(desc(total))

n_orders <- nrow(order_totals)
if (n_orders > length(categorical_palette)) {
  message(sprintf(
    "%d orders present — the top %d keep their own color; the remaining %d are folded into \"Other.\"",
    n_orders, length(categorical_palette), n_orders - length(categorical_palette)
  ))
  keep_orders <- order_totals$order[seq_len(length(categorical_palette))]
  order_counts <- order_counts %>%
    mutate(order_grouped = ifelse(order %in% keep_orders, order, "Other")) %>%
    group_by(order_grouped, distance_bin) %>%
    summarise(n_species = sum(n_species), .groups = "drop") %>%
    rename(order = order_grouped)
  order_levels <- c(keep_orders, "Other")
  order_colors <- setNames(c(categorical_palette[seq_len(length(keep_orders))], other_color), order_levels)
} else {
  order_levels <- order_totals$order
  order_colors <- setNames(categorical_palette[seq_len(n_orders)], order_levels)
}

order_counts <- order_counts %>%
  mutate(order = factor(order, levels = order_levels),
         distance_bin = factor(distance_bin, levels = bin_levels))

order_plot <- ggplot(order_counts, aes(x = distance_bin, y = n_species, fill = order)) +
  geom_col(position = position_dodge2(preserve = "single", padding = 0.15), width = 0.85) +
  scale_fill_manual(values = order_colors, name = "Order") +
  scale_y_continuous(breaks = integer_breaks, expand = expansion(mult = c(0, 0.08))) +
  labs(
    title = "In-extent Arthropoda species by order and distance to the Dangermond Preserve",
    subtitle = "Each species' true closest record, including records outside the latitudinal band",
    x = "Distance to Preserve boundary",
    y = "Number of species"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "grey88", linewidth = 0.3),
    axis.text.x = element_text(angle = 20, hjust = 1),
    plot.title = element_text(face = "bold", size = 12),
    plot.subtitle = element_text(size = 10, color = "grey35")
  )

ggsave(outfile_order_chart, order_plot, width = 9, height = 5.5, dpi = 300)
message(sprintf("Order chart written to:\n  %s", outfile_order_chart))

# ------------------------------------------------------------
# 5) Order+family chart — same frame as the order chart (distance bin
#    on the x-axis, one dodged bar per order per bin), but each bar is
#    stacked into family segments shaded from that order's base color.
#    See "ORDER+FAMILY CHART DESIGN" above for how the dodge+stack
#    combination and the legend are built, since ggplot2 has no single
#    position for both at once.
# ------------------------------------------------------------
message("\nBuilding order+family stacked chart...")

# Same order grouping/coloring as the order chart above, applied fresh
# here so this section doesn't depend on variables built only inside
# the `if` branch above.
order_family_counts <- df_binned %>%
  mutate(order_grouped = if (n_orders > length(categorical_palette)) {
    ifelse(order %in% keep_orders, order, "Other")
  } else {
    order
  }) %>%
  group_by(order_grouped, family, distance_bin) %>%
  summarise(n_species = n_distinct(.data[[species_col]]), .groups = "drop") %>%
  rename(order = order_grouped) %>%
  mutate(order = factor(order, levels = order_levels))

# Family shade assignment: within each order, sort its families by
# descending total species count (across all bins) and generate that
# many shades from the order's full base color down to a lightened
# tint — the most numerous family gets the fullest color.
#
# lighten_amount uses ifelse() (vectorized), not if()/else(), because
# n_families_in_order is a per-row value recycled across each group by
# a grouped mutate() — for any order with more than one family it's a
# vector, not a scalar, and a base if() on a vector of length > 1
# errors. Caught by actually running the script against test data, not
# by reading the code — see the Step 7 README for details.
family_shade_lookup <- order_family_counts %>%
  group_by(order, family) %>%
  summarise(family_total = sum(n_species), .groups = "drop") %>%
  arrange(order, desc(family_total)) %>%
  group_by(order) %>%
  mutate(
    n_families_in_order = n(),
    shade_rank = row_number(), # 1 = most numerous family in this order
    lighten_amount = ifelse(n_families_in_order == 1, 0, (shade_rank - 1) / (n_families_in_order - 1) * 0.65),
    base_hex = order_colors[as.character(order)],
    segment_color = mapply(lighten_hex, base_hex, lighten_amount),
    legend_label = paste0(order, ": ", family)
  ) %>%
  ungroup() %>%
  arrange(order, shade_rank)

segment_colors <- setNames(family_shade_lookup$segment_color, family_shade_lookup$legend_label)
segment_levels <- family_shade_lookup$legend_label # order-then-shade order, so the
                                                    # legend groups each order's
                                                    # families together, darkest first

# Manual dodge offsets: every order gets a fixed-width slot at every
# bin (same set of slots across all bins, mirroring position_dodge2's
# preserve="single" behavior in the order chart above), and family
# segments stack within that slot via geom_col's default stacking,
# since every (order, bin) pair now has a unique numeric x position.
n_order_slots <- length(order_levels)
slot_width <- 0.9 / n_order_slots
bar_width <- slot_width * 0.85
order_offset <- setNames(
  (seq_len(n_order_slots) - (n_order_slots + 1) / 2) * slot_width,
  order_levels
)

order_family_counts <- order_family_counts %>%
  mutate(
    legend_label = factor(paste0(order, ": ", family), levels = segment_levels),
    x_numeric = as.numeric(factor(distance_bin, levels = bin_levels)) + order_offset[as.character(order)]
  )

# Unlike the order chart above, this chart fakes a discrete x-axis with
# manually-computed continuous positions (see the dodge-offset math
# above), so ggplot has no real per-bin grouping to center labels under
# automatically. Two things restore that visual anchor, since without
# them a bar sitting near the edge of its dodge slot could plausibly be
# misread as belonging to the neighboring bin, especially with angled
# label text: explicit tick marks at each bin's true center (re-enabled
# below — theme_minimal() removes them by default), and a faint
# vertical divider at each bin *boundary* (half-integer positions,
# drawn first so bars painted on top of it leave a visible gap only in
# the empty space between bins).
bin_boundaries <- seq(1.5, length(bin_levels) - 0.5, by = 1)

order_family_plot <- ggplot(order_family_counts,
                             aes(x = x_numeric, y = n_species, fill = legend_label)) +
  geom_vline(xintercept = bin_boundaries, color = "grey85", linewidth = 0.3) +
  geom_col(width = bar_width, position = "stack") +
  scale_fill_manual(values = segment_colors, name = "Order: Family") +
  scale_x_continuous(
    breaks = seq_along(bin_levels),
    labels = bin_levels,
    expand = expansion(add = 0.6)
  ) +
  scale_y_continuous(breaks = integer_breaks, expand = expansion(mult = c(0, 0.08))) +
  labs(
    title = "In-extent Arthropoda species by order, family, and distance to the Dangermond Preserve",
    subtitle = "Each order's bar is segmented by family, shaded from that order's color (darkest = most species)",
    x = "Distance to Preserve boundary",
    y = "Number of species"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "grey88", linewidth = 0.3),
    axis.text.x = element_text(angle = 20, hjust = 1),
    axis.ticks.x = element_line(color = "grey50", linewidth = 0.3),
    axis.ticks.length.x = unit(0.15, "cm"),
    legend.key.size = unit(0.3, "cm"),
    legend.text = element_text(size = 6),
    plot.title = element_text(face = "bold", size = 12),
    plot.subtitle = element_text(size = 10, color = "grey35")
  )

# RUNAWAY IMAGE HEIGHT BUG — found only by running this against the real,
# full dataset (California's actual Arthropoda diversity), not by
# reviewing the code or the synthetic test cases in this step's README:
# the original height formula (5.5 + 0.15in per order:family legend row)
# was sized for a handful of families per order, which is all the
# synthetic test data ever had. Real data produced 1,031 distinct
# order:family combinations, so the formula asked ggsave() for a
# ~160-inch-tall, ~48,000-pixel image — technically renders, but it's
# unusable as a figure and was rejected outright by the file-delivery
# tool (upload error) for being an absurd size. A one-row-per-family
# legend simply cannot scale to real-world taxonomic diversity.
#
# Fix: cap the image at a fixed, always-reasonable height regardless of
# how many order:family combinations are present, and let the legend
# wrap into multiple columns (via guide_legend(ncol = ...)) so it uses
# the available height instead of dictating it. This keeps the chart
# itself (the bars, the part that actually needs to be readable)
# properly sized; with 1,000+ legend entries the legend itself is
# necessarily dense text, not something any static image size fixes —
# species_by_order_family_distance.csv (the full table this chart
# summarizes) is the place to look up exact order/family/bin counts,
# same relationship Step 7's own header comments already describe
# between this chart and that table.
max_height_in <- 22
legend_ncol <- max(1, ceiling(nrow(family_shade_lookup) / 90))

order_family_plot <- order_family_plot +
  guides(fill = guide_legend(ncol = legend_ncol))

ggsave(outfile_order_family_chart, order_family_plot,
       width = 10 + 1.4 * (legend_ncol - 1), height = max_height_in, dpi = 300, limitsize = FALSE)
message(sprintf("Order+family chart written to:\n  %s", outfile_order_family_chart))

message("\nDone.")
